### PR TITLE
chore: Upgrade `@logdna/logger`

### PR DESCRIPTION
**Pull request by bukinoshita**
Upgrade `logdna/logger` in order to fix the security issue https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

### CODE REVIEW

**Comment by mdeltito** [comment]
@logdnabot please test

**Comment by bukinoshita** [comment]
Is there anything I can do here?

**Comment by mdeltito** [comment]
@bukinoshita sorry for the delay here, I've opened #15 which resolves the CI issues along with bumping the dependency. thank you for bringing this to our attention!

**Comment by mdeltito** [comment]
closed in favor of #15

**Pull request closed without merging**
